In [7]:
!open .

In [1]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


In [2]:
%gui qt

ERROR:root:Cannot activate multiple GUI eventloops


In [3]:
from playground.view import maze_view

/Users/laic/opt/anaconda3/lib/python3.7/site-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm
/Users/laic/Work/pydev/smart/vispy/vispy/visuals/line/line.py:392: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('color', np.float32, 4)])
/Users/laic/Work/pydev/smart/vispy/vispy/visuals/line/arrow.py:55: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('linewidth', np.float32, 1)
INFO:numexpr.utils:NumExpr defaulting to 8 threads.


In [4]:
nav = maze_view()

/Users/laic/Work/pydev/smart/vispy/vispy/visuals/markers.py:563: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  ('a_edgewidth', np.float32, 1)])


In [5]:
nav.show()

INFO:OpenGL.acceleratesupport:OpenGL_accelerate module loaded
INFO:OpenGL.arrays.arraydatatype:Using accelerated ArrayDatatype


In [8]:
# type o to load_maze

In [6]:
nav.load_animal()

In [10]:
nav.maze.coord['Origin']

(-1309.21, -1258.16, 0.0)

In [11]:
origin = np.array(nav.maze.coord['Origin']).astype(np.float32)

In [12]:
origin[0], origin[1]

(-1309.21, -1258.16)

In [13]:
nav.origin

array([130921., 125816.,     -0.], dtype=float32)

In [17]:
nav.current_pos = nav.origin
nav.current_hd = 90

In [33]:
nav.current_pos += np.array([1000,1000,0])

In [18]:
nav.arrow_len=4000

In [16]:
nav.current_hd += 15
nav.current_hd

105

In [16]:
nav.current_pos += np.array([200,200,0])
nav.current_hd -= 10

In [17]:
nav.current_pos[:2]

array([131117., 126014.], dtype=float32)

In [24]:
hd_in = nav.current_hd
arrow_delta = np.array([np.sin(hd_in/360*np.pi*2), np.cos(hd_in/360*np.pi*2)])
arrow = np.vstack(( nav.current_pos[:2], 
                    nav.current_pos[:2] + nav._arrow_len * arrow_delta) ) 
arrow

array([[261803., 261803.],
       [261803., 263803.]])

In [122]:
nav.arrow.set_data(arrow)

In [65]:
nav.mirror=False

In [19]:
nav.x_range = [nav.origin[0]-10000, nav.origin[0]+10000]
nav.y_range = [nav.origin[1]-10000, nav.origin[1]+10000]

In [19]:
nav.posterior = np.random.randn(40, 40)

In [29]:
nav.image.visible = True